spring.application.name=request-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/govflow
spring.datasource.username=govflow
spring.datasource.password=govflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,metrics